// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrorwppjbtftlhbkysqz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyb3J3cHBqYnRmdGxoYmt5c3F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODI3ODIsImV4cCI6MjA2NDQ1ODc4Mn0.p7mCUBQSRE-knmoX_h-n6PDsYiyOYNGmqEqCyBh6uxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);